---
stages:
  - initialize

Setup_Clients_Env:
  stage: initialize
  image:
    name: centos:latest
  script:
    - yum install -y epel-release
    - yum install -y ansible docker-client
    - ansible all -i hosts -c docker -m ping
    - ansible-playbook -i hosts -c docker clients.yml
