---
- hosts: all
  gather_facts: false
  connection: docker
  tasks:
    - yum:
        name: "{{ item }}"
        state: latest
      loop:
        - openssh-server
        - openssh-clients
        - sudo

    - systemd:
        name: sshd
        state: started
        enabled: true

    - user:
        name: vagrant

    - files:
        path: /home/vagrant/.ssh
        state: directory
        mode: 0700
        owner: vagrant
        group: vagrant

    - copy:
        src: authorized_keys
        dest: /home/vagrant/.ssh/authorized_keys
        mode: 0644
        owner: vagrant
        group: vagrant
