---
- hosts: all
  gather_facts: false
  tasks:
    - yum:
        name: "{{ item }}"
        state: latest
      loop:
        - openssh-server
        - openssh-clients
        - sudo

    - systemd:
        name: sshd
        state: started
        enabled: true

    - user:
        name: vagrant
        groups: vagrant,wheel

    - file:
        path: /home/vagrant/.ssh
        state: directory
        mode: 0700
        owner: vagrant
        group: vagrant

    - copy:
        src: authorized_keys
        dest: /home/vagrant/.ssh/authorized_keys
        mode: 0644
        owner: vagrant
        group: vagrant

- hosts: works
  gather_facts: true
  tasks:
    - yum:
        name: "{{ item[0] }}"
        state: "{{ item[1] | default('latest') }}"
      loop:
        - vim
        - which
        - tree
        - git
        - epel-release
        - [ "ansible", "2.4.3.0" ]
        - [ "ansible-lint" , "3.4.21" ]

    - systemd:
        name: sshd
        state: started
        enabled: true

    - file:
        path: "/home/vagrant/{{ item }}"
        state: directory
        mode: 0700
        owner: vagrant
        group: vagrant
      loop:
        - vagrant/infraci/.vagrant/machines/gitlab/virtualbox
        - vagrant/infraci/.vagrant/machines/gitlab-runner/virtualbox

    - copy:
        src: private_key
        dest: "/home/vagrant/{{ item }}/private_key"
        mode: 0600
        owner: vagrant
        group: vagrant
      loop:
        - vagrant/infraci/.vagrant/machines/gitlab/virtualbox
        - vagrant/infraci/.vagrant/machines/gitlab-runner/virtualbox

    - lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^vagrant\s'
        line: 'vagrant ALL=(ALL) NOPASSWD: ALL'
