version: "3.6"

x-template: &template
  image: centos:7.3.1611
  privileged: true
  command: /sbin/init
  restart: always

services:
  gitlab:
    image: gitlab/gitlab-ce:10.8.4-ce.0
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.33.10'
        gitlab_rails['time_zone'] = 'Asia/Tokyo'
        gitlab_rails['initial_root_password'] = 'password'
        gitlab_rails['initial_shared_runners_registration_token'] = 'token-ABC'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        unicorn['worker_timeout'] = 60
        unicorn['worker_processes'] = 3
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./volume/data:/var/opt/gitlab
    networks:
      infraci_nw:
        ipv4_address: 192.168.33.10
  gitlab-runner:
    image: gitlab/gitlab-runner:v10.8.0
    container_name: gitlab-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      infraci_nw:
        ipv4_address: 192.168.33.11
  client1:
    <<: *template
    container_name: client1
    ports:
      - "8082:80"
    networks:
      infraci_nw:
        ipv4_address: 192.168.33.12
  client2:
    <<: *template
    container_name: client2
    ports:
      - "8083:80"
    networks:
      infraci_nw:
        ipv4_address: 192.168.33.13
  client3:
    <<: *template
    container_name: client3
    ports:
      - "8084:80"
    networks:
      infraci_nw:
        ipv4_address: 192.168.33.14
  client4:
    <<: *template
    container_name: client4
    ports:
      - "8085:80"
    networks:
      infraci_nw:
        ipv4_address: 192.168.33.15
  console:
    <<: *template
    container_name: console
    ports:
      - "2222:22"
    networks:
      infraci_nw:
        ipv4_address: 192.168.33.99

networks:
  infraci_nw:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.33.0/24
